package concordia.dems.communication;

/**
* concordia/dems/communication/IEventManagerCommunicationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/java-photon/eclipse/workspace/Corba-6231/src/concordia/dems/communication/ManagerCommunication.idl
* Friday, June 21, 2019 9:08:33 PM EDT
*/

public final class IEventManagerCommunicationHolder implements org.omg.CORBA.portable.Streamable
{
  public concordia.dems.communication.IEventManagerCommunication value = null;

  public IEventManagerCommunicationHolder ()
  {
  }

  public IEventManagerCommunicationHolder (concordia.dems.communication.IEventManagerCommunication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = concordia.dems.communication.IEventManagerCommunicationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    concordia.dems.communication.IEventManagerCommunicationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return concordia.dems.communication.IEventManagerCommunicationHelper.type ();
  }

}
