package concordia.dems.communication;


/**
* concordia/dems/communication/IEventManagerCommunicationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from M:/Concordia/couse.project/project.java.workspace/Corba-6231/src/concordia/dems/communication/ManagerCommunication.idl
* Friday, June 21, 2019 6:07:15 PM EDT
*/

public interface IEventManagerCommunicationOperations 
{
  String performOperation (String userRequest);
} // interface IEventManagerCommunicationOperations
