package concordia.dems.communication;


/**
* concordia/dems/communication/IEventManagerCommunication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/java-photon/eclipse/workspace/Corba-6231/src/concordia/dems/communication/ManagerCommunication.idl
* Friday, June 21, 2019 9:08:33 PM EDT
*/

public interface IEventManagerCommunication extends IEventManagerCommunicationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IEventManagerCommunication
