package concordia.dems.communication;


/**
* concordia/dems/communication/IEventManagerCommunicationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from F:/java-photon/eclipse/workspace/Corba-6231/src/concordia/dems/communication/ManagerCommunication.idl
* Friday, June 21, 2019 9:08:33 PM EDT
*/

abstract public class IEventManagerCommunicationHelper
{
  private static String  _id = "IDL:concordia/dems/communication/IEventManagerCommunication:1.0";

  public static void insert (org.omg.CORBA.Any a, concordia.dems.communication.IEventManagerCommunication that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static concordia.dems.communication.IEventManagerCommunication extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (concordia.dems.communication.IEventManagerCommunicationHelper.id (), "IEventManagerCommunication");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static concordia.dems.communication.IEventManagerCommunication read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IEventManagerCommunicationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, concordia.dems.communication.IEventManagerCommunication value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static concordia.dems.communication.IEventManagerCommunication narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof concordia.dems.communication.IEventManagerCommunication)
      return (concordia.dems.communication.IEventManagerCommunication)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      concordia.dems.communication._IEventManagerCommunicationStub stub = new concordia.dems.communication._IEventManagerCommunicationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static concordia.dems.communication.IEventManagerCommunication unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof concordia.dems.communication.IEventManagerCommunication)
      return (concordia.dems.communication.IEventManagerCommunication)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      concordia.dems.communication._IEventManagerCommunicationStub stub = new concordia.dems.communication._IEventManagerCommunicationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
