package concordia.dems.communication;


/**
* concordia/dems/communication/IEventManagerCommunicationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from M:/Concordia/couse.project/project.java.workspace/Corba-6231/src/concordia/dems/communication/ManagerCommunication.idl
* Friday, June 21, 2019 6:07:15 PM EDT
*/

public abstract class IEventManagerCommunicationPOA extends org.omg.PortableServer.Servant
 implements concordia.dems.communication.IEventManagerCommunicationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("performOperation", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // concordia/dems/communication/IEventManagerCommunication/performOperation
       {
         String userRequest = in.read_string ();
         String $result = null;
         $result = this.performOperation (userRequest);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:concordia/dems/communication/IEventManagerCommunication:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IEventManagerCommunication _this() 
  {
    return IEventManagerCommunicationHelper.narrow(
    super._this_object());
  }

  public IEventManagerCommunication _this(org.omg.CORBA.ORB orb) 
  {
    return IEventManagerCommunicationHelper.narrow(
    super._this_object(orb));
  }


} // class IEventManagerCommunicationPOA
